<%@ Page Language="C#" MasterPageFile="~/ADMIN/ADMINMASTER.Master" AutoEventWireup="true" CodeBehind="User_Details.aspx.cs" Inherits="RTOSYSTEM.ADMIN.WebForm4" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<table align="center" style="height: 187px">
 <tr>
            <td align="center">
                <asp:TextBox ID="TextBox1" PlaceHolder="User Id:" runat="server"></asp:TextBox>
                <asp:Button ID="Button1" runat="server" Text="Search" onclick="Button1_Click" />
            </td>
       </tr>
      <tr>
        <td>
              <asp:GridView ID="GridView2" runat="server" 
                BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" 
                CellPadding="3" GridLines="Horizontal" AutoGenerateDeleteButton="True" 
              
                DataKeyNames="user_id"  
                AutoGenerateColumns="False" 
                   >
                <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
                <Columns>
                    <asp:BoundField DataField="user_id" HeaderText="User Id" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="user_name" HeaderText="User Name">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="first_name" HeaderText="First name">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="last_name" HeaderText="Last name">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="dob" HeaderText="D.O.B">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="address" HeaderText="Address">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="city" HeaderText="City" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="mobile" HeaderText="Mobile" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="email" HeaderText="E-Mail" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="q1" HeaderText="Question1" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="q2" HeaderText="Question2" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="q3" HeaderText="Question3">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="pwd" HeaderText="Password">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="retype_pwd" HeaderText="Retype-Password">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                </Columns>
                <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
                <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
                <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
                <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
                <AlternatingRowStyle BackColor="#F7F7F7" />
            </asp:GridView>
            <asp:GridView ID="GridView1" runat="server" 
                BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" 
                CellPadding="3" GridLines="Horizontal" AutoGenerateDeleteButton="True" 
               onrowdeleting="GridView1_RowDeleting"  
                DataKeyNames="user_id"  
                AutoGenerateColumns="False" >
                <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
                <Columns>
                    <asp:BoundField DataField="user_id" HeaderText="User Id" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="user_name" HeaderText="User Name">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="first_name" HeaderText="First name">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="last_name" HeaderText="Last name">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="dob" HeaderText="D.O.B">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="address" HeaderText="Address">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="city" HeaderText="City" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="mobile" HeaderText="Mobile" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="email" HeaderText="E-Mail" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="q1" HeaderText="Question1" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="q2" HeaderText="Question2" >
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="q3" HeaderText="Question3">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="pwd" HeaderText="Password">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                    <asp:BoundField DataField="retype_pwd" HeaderText="Retype-Password">
                        <ItemStyle HorizontalAlign="Center" Width="210px" />
                    </asp:BoundField>
                </Columns>
                <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
                <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
                <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
                <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
                <AlternatingRowStyle BackColor="#F7F7F7" />
            </asp:GridView>
    <br />
<br />
    </td>
      </tr>
 </tabel>
</asp:Content>
